sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  on_failure: change
node_js:
- node
before_script:
- npm prune
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
after_success:
  - npm run semantic-release:pre
deploy:
  provider: npm
  email: paul@musso.io
  skip_cleanup: true
  api_key:
    secure: FHc5y1MgbdwfX6Q6dT5pePUSxhDoa4L30zAFhnHmusI9E2UXsC6jCIUXE9V9+EVvYnuOfAQcxDnuzdaGdhbsLOS/ActtvncmK0EXxzMInG/7ZoQkX1qkdKYMMTV4RbOC8qjHfS5dBdTEXfgwPnqJWsrqy1H1TP8nchgKxAiUZQKAxXxckQ9Z299IpiFVXa5MFVF25BGUa0e5HESDDEKWq9P8UHxOvmh9HhrvtS3T/hTe/qqkdGOSKp0f1DCRKykSs6qQgWYds4rR9UjXWbgiE06J9cpujP08FggXWQl7W4yuqBJYNfl3r8pdrMuNzB3iKcCCzZxm3kOwGpRAYpKSLOS1C7yNyLB67yUQh4FaNbts0h+qY1vJxDkMpuq05di2WBIWL6nOF4YG9uWYVMg8c67CtHFAhfF/iMLcldaopaAxSLuu36vEorCgdu7Ud9lfkQNl4Gy/BSYjINgDwnrKv8EldvVP3fwoLpTas93JqUQbC5OzbY4CcV1YBQE1nGDdlaE5GLgs1ZFPp6XYeyCtZuy7xi0zmGPfQET9odaMcslkmjal805btk9ZJxjDfieq6b0Wv4WasI6rpkwe0naiDY/Qk86bod2dKhJGTPmQFJeZajACeVmRaesUqbhOrR2oZvP4PUPM3TkNKCkapxvEdorGCm2xuwOHXxbeklya8vY=
  on:
    tags: true
    repo: popul/eslint-plugin-reselect
    branch: master
after_deploy:
  - npm run semantic-release:post
